// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkZklizpLoYAUWgNRigR0p4eRpQvbfaHY',
    appId: '1:367375272160:web:a8229eb8e8954aad89a885',
    messagingSenderId: '367375272160',
    projectId: 'flutter-html-web-ide',
    authDomain: 'flutter-html-web-ide.firebaseapp.com',
    storageBucket: 'flutter-html-web-ide.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIsFsaJdtU540wUQWg9IJpXkLAv27ds0c',
    appId: '1:367375272160:android:a922cd66abd6950d89a885',
    messagingSenderId: '367375272160',
    projectId: 'flutter-html-web-ide',
    storageBucket: 'flutter-html-web-ide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkXSVLHeouJLMndsWXFl0nSjEc04M_-5I',
    appId: '1:367375272160:ios:3d7953830ffc53e589a885',
    messagingSenderId: '367375272160',
    projectId: 'flutter-html-web-ide',
    storageBucket: 'flutter-html-web-ide.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkXSVLHeouJLMndsWXFl0nSjEc04M_-5I',
    appId: '1:367375272160:ios:f2d87588749ebe4789a885',
    messagingSenderId: '367375272160',
    projectId: 'flutter-html-web-ide',
    storageBucket: 'flutter-html-web-ide.firebasestorage.app',
    iosBundleId: 'com.example.pythonWebIde',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkZklizpLoYAUWgNRigR0p4eRpQvbfaHY',
    appId: '1:367375272160:web:c58305a28e2c656689a885',
    messagingSenderId: '367375272160',
    projectId: 'flutter-html-web-ide',
    authDomain: 'flutter-html-web-ide.firebaseapp.com',
    storageBucket: 'flutter-html-web-ide.firebasestorage.app',
  );
}
